### ISSUE TITLE
Documentation about the columns in jamonadmin.jsp

### ISSUE THREAD

**Issue by paulwellnerbou** [stevensouza/jamonapi#13]
I have some doubts about the numbers displayed in the table of jamonadmin.jsp, is there any documentation about the numbers in the different columns? The main question I have is: What is the unit, are we talking about request duration? Or requests per time unit?
- Hits: I assume the absolute number of hits of this URL
- Avg: The average time in milliseconds?
- Total: The total time in milliseconds?

**Comment by stevensouza** [comment]
The short answer is that your interpretation is correct.
- for start/stop the units are "ms.".  
- 'Hits' is the absolute number of hits/counts for the url (or for whatever you are tracking)
- 'Avg' is the average time in milliseconds for the given page.
- 'Total' is the total time for the url in milliseconds.

Keep in mind that jamon can measure other thing via the 'MonitorFactory.add(...)' method (such as exceptions, method performance, MB, $) so in these cases avg and total represent averages and totals in these units.

The units column is also displayed in the jamonadmin.jsp report after the label.  For example "myhomepage.jsp, ms.".  See examples in the 'label' column in this view of the jamonadmin.jsp page: http://jamonapi.sourceforge.net/jamon_war_admin.png.  Having said that you can also time things in nanoseconds if that is your preference.  Jamon supports this, but not by default.  

Here is some more information:
- explanation of columns and example - http://jamonapi.sourceforge.net/additional_example.html
- intro video talking about columns (marked around the place it talks about the columns, but for new users the whole video would be useful) - https://youtu.be/fKooex0ZPcw?t=28s

Let me know if you have more questions.
Steve

**Comment by paulwellnerbou** [comment]
Thanks, this helped!
