### ISSUE TITLE
fdsapi NoSuchMethodError com.jamonapi.MonitorFactory.getDebugFactory

### ISSUE THREAD

**Issue by xrisdevs** [stevensouza/jamonapi#17]
I'm trying to get my Object[][] data from MonitorFactory getData() and then passing it to .getFormattedDataSet(...) and when I do I get NoSuchMethodError com.jamonapi.MonitorFactory.getDebugFactory ... I'm sure all the classpath and everything is added.

**Comment by stevensouza** [comment]
Make sure you have the fdsapi-1.2.jar available.  The formatteddataset code is in there.  As i recall it comes bundled in the war, but if you are running the code outside the jamon war that jar would not be available.

Here is the link to the jar... https://github.com/stevensouza/jamonapi/blob/master/jamon_war/src/main/webapp/WEB-INF/lib/fdsapi-1.2.jar

**Comment by stevensouza** [comment]
If that doesn't answer your question can you please post your code?

Thanks,
Steve
