### ISSUE TITLE
distribute tracing support in jamon

### ISSUE THREAD

**Issue by bwzhang2011** [stevensouza/jamonapi#3]
@stevensouza, many thanks for great product like jamon to provide us monitor features among our projects with so many cases. what's more,  compared with zipkin somewhat implementation of Google dapper protocol used for distributing trace. if jamon has the plan for dapper support, it will be more grateful to bring in more tracing features to let the monitor info model of jamon to be transferred to many log platform like flume with elastic integration for analysis and access.  as jamon take the first step for hazelcast integration to support distributing project integration, so I dare say that jamon could take such into consideration to make it step further.  I know in such area like Brave (https://github.com/kristofa/brave)  has done something similar to zipkin. so I think jamon could do even better to bring in distribute tracing not long in the future.

**Comment by stevensouza** [comment]
Thanks for the kind words. 

I hadn't heard of zipkin.  What would you like jamon to do with zipkin and how would you use it?

Thanks,
Steve

**Comment by bwzhang2011** [comment]
@stevensouza, zipkin (https://github.com/twitter/zipkin) originates from twitter as the implementation for Dapper Protocol of Google(http://research.google.com/pubs/pub36356.html) as the distribute tracing solution(http://twitter.github.io/zipkin/).  the suggestion for jamon to add such feature is such could be called chaining calls tracing that is from the entrance for tracing start to the exit for tracing off. if reached, it could cover the whole calling procedure for analysis. and it will lead to the calling tree for each request and response and could be integrated with many framework for monitoring.

**Comment by bwzhang2011** [comment]
we knew that jamon has set up solid abstract monitor layer to be integrated with many containers and trying to make it around cluster but it did lack of the chaining tracing support. and it will be very useful in distribute rpc way integrated with many projects deployed in different nodes and we just want to trace the whole.

**Comment by stevensouza** [comment]
<<the suggestion for jamon to add such feature is such could be called chaining calls tracing that is from the entrance for tracing start to the exit for tracing off.>>
Could you further explain what you mean here?  Giving and example and sample data would help. Have you worked with jamon listeners yet?  They might be able to work here. Can you also give a sample program showing zipkin and what you would like to do with it?  If possible use maven.

Currently, i am swamped with other projects.   I am not sure when i can get to this so any contribution that you can make would speed things along.

Do you work with StatsD?  Is that similar to zipkin?

Steve

**Comment by bwzhang2011** [comment]
@stevensouza,sorry for late response.  first I think distributing tracing with jamon will be some fantastic feature if adopted but with many work to do, second I'm still new comer to such domain and just leave suggestion if you take interest in when you spare your time to take a look at the dapper protocol as I commented above. third, I'm not aware of StatsD, frankly speaking, jamon is similar to metrics. what's more,  zipkin is such based on scala which most of us not familiar and from the api design jamon seems more light to understand so here came the issue.

**Comment by bwzhang2011** [comment]
@stevensouza, I think such issue should be closed. as jamon is not the right place to implement distribute tracing. and if any idea came up it should be reopen and give it try.
