### ISSUE TITLE
distribute monitor enhancement with hazelcast

### ISSUE THREAD

**Issue by bwzhang2011** [stevensouza/jamonapi#4]
@stevensouza, thanks for integration with hazelcast for distribute application monitor. during integration among our projects. I found we should enhance for such integration. as jamon will ship the jamondata with hazelcast map with configured time as the time task, here comes my doubt that. 
first, the jamon-war seems to be considered as the center location with hazelcast cluster (as the server instance of hazelcastInstance), it will be in charge of the hazelcast map to be prevented from data loss and load the data for monitor.

second, the application to be monitored should make the integration with jamon-war, like the hazelcast client connecting to the hazelcast instance

third, I notice that the data persistor does not use the hazelcastclient way for communication and configuration which could not know how to make the communication.

so would you mind leaving us more for distribute application monitoring, as most cases is 
1. we just need the monitor server (just like the hazelcast cluster)to monitor different application deployed in different node
1. different node with jamon integration could make connection with the monitor server(deployed with jamon war) and it doesn't need to rely on jamonwar itself, for it could be considered as the monitor provider while monitor server to be the consumer one.
2. if monitor server dies, it would not impact the node.

looking forward to your reply soon and leave us more suggestion if you could spare your time.

**Comment by stevensouza** [comment]
Hi, thanks for the posting.  I am having a difficult time understanding the english though.  What is the problem you are trying to solve?

**Comment by bwzhang2011** [comment]
@stevensouza, sorry for my words to make you feel puzzle about my points. here comes my doubt and suggestion.
First, I just want to make jamon-war as the monitor node with hazelcast server (maybe it could be grouped as cluster)role to monitor the applications connected.
Second, If the monitor node and application node is apart, I think the application node should use hazelcast client api to connect the monitor node and try to pass the monitor data into the IMap structure from the cluster. as from the resource code of JamonServletContextListener, I found it was hard to make the hazelcast configurable and maybe it lacks the support the hazelcast client.
Third, in read world, most of our projects will make full use of the AOP or Interceptor for the api that could be monitored and try to make the monitor data persist through e.g hazelcast, that's my point as above.
at last, look forward to your reply and help me solve such problem.

**Comment by bwzhang2011** [comment]
@stevensouza, any update with such issue or something need to be more clear about this ?

**Comment by stevensouza** [comment]
Thanks for your input.  It still isn't clear to me though.  I would have no idea what to implement based on your feedback.  Your statements are vague and abstract, so it is hard for me to know what you are after and what problems you are trying to solve.  

**"First, I just want to make jamon-war as the monitor node with hazelcast server (maybe it could be grouped as cluster)role to monitor the applications connected."**

What does monitor node mean to you?  What would it be responsible for?  What do you mean grouped as a cluster?  What applications are you referring to?  How would the applications connect and what are they connecting to?  

**"Second, If the monitor node and application node is apart, I think the application node should use hazelcast client api to connect the monitor node and try to pass the monitor data into the IMap structure from the cluster. "**
Maybe giving an example in pseudo code would be helpful here.  

**"Third, in read world, most of our projects will make full use of the AOP or Interceptor for the api that could be monitored and try to make the monitor data persist through e.g hazelcast, that's my point as above."**
I am not sure what you mean here.  You can use aop, and interceptors with jamon.

**Comment by bwzhang2011** [comment]
@stevensouza, you'r right just as I didn't ignore your consideration out of your original purpose of jamon. here comes my further introduction about my suggestion.

For the First one, the monitor node most time means that the monitor war application just like the deployment with jamon-war to show the monitor resources as it collected from monitor data from jamon api.
as current implementation of jamon, if it integrated with hazelcast it will start as hazelcast default configuration (launched at port 5701), if more deployed in the same machine, it will grouped together with port increment started from 5701(like 5701, 5702 etc).  as hazelcast provides us xml
file to be launched with its programmatic api or with hazelcast-spring as we also want to set some connecting info like group name and group password for connecting.

For  the second one, if above confirmed with monitor-node with jamon-war or something similar, the application part should act as the monitor data provider which make full use of jamon-api to collect the monitor info and try to make it persist from the api also, if with hazelcas integration, it will call the hazelcast client to connect to the monitor node. and there will be a lot of applications to be monitored  and those will make a attempt to connect to the monitor node.

For the last, what I expressed is just as you pointed out, for the second part one, the application will refer to jamon proxy or aop way to create the monitor layer to collect the monitor data.

As the conclusion, I just want to point out my consideration towards the usecase of jamon not out of the design for jamon. to some aspect, we're appreciated of the simplicity or strong monitor feature provided from jamon. we just want to make it more real world in our projects. that's we want to monitor our projects with less code and configuration. so if we make them apart, the monitor node takes the responsibility of showing the monitor data (just as the consumer) while the application one takes the provider one.

**Comment by bwzhang2011** [comment]
@stevensouza, any update with such issue ?

**Comment by bwzhang2011** [comment]
@stevensouza, would mind spare your suggestion or idea if you could spare your time. the reason for such is for some enterprise application, he will produce his monitor application with the special resources as defined to form a centralized one. so other application even without web resource just some proc id application with shell script would be also appreciated of being monitored and uploaded such data for the monitor server.so the server side will generate more map to hold such data from different application.
