### ISSUE TITLE
Instructions for Jetty 9 are incorrect

### ISSUE THREAD

**Issue by joakime** [stevensouza/jamonapi#5]
The instructions for Jetty 9 are incorrect.

See https://github.com/stevensouza/jamonapi/blob/master/src/JAMonUsersGuide/http_monitoring.html#L86-L100

The way to enable jamon on Jetty 9 is to make your modifications to your ${jetty.base} directory, not to modify the ${jetty.home} (aka distribution directory).
- There is no `lib/etc` directory, either in Jetty 8 or Jetty 9.
- In your ${jetty.base} directory...
  - add support for the `ext` module - `$java -jar /path/to/jetty-dist/start.jar --add-to-start=ext`
  - create a ${jetty.base}/etc directory
  - add your ${jetty.base}/etc/jamon.xml file that adds the handler (or wraps it in a similar way like the [jetty-rewrite.xml](https://github.com/eclipse/jetty.project/blob/master/jetty-rewrite/src/main/config/etc/jetty-rewrite.xml) does)
  - add the line `etc/jamon.xml` to your ${jetty.base}/start.ini

Also note: Jetty 9.3 comes with [jamon as a module](https://github.com/eclipse/jetty.project/blob/master/jetty-distribution/src/main/resources/modules/jamon.mod), you can choose to take it over if you wish (just don't forget about the [etc/jamon.xml](https://github.com/eclipse/jetty.project/blob/master/jetty-distribution/src/main/resources/etc/jamon.xml)).

**Comment by joakime** [comment]
Note: the jamon.mod (at jetty) downloads the needed libs into your ${jetty.base} via the maven central repository (see [files] section).   It also sets up jamon at the appropriate point in the startup lifecycle (done via the information graph from the listed dependencies)

**Comment by stevensouza** [comment]
Thanks for you input. That will be helpful for jamon users.  I will give it a try too.

Thanks!
Steve
