### ISSUE TITLE
Exception listener

### ISSUE THREAD

**Issue by robertotru** [stevensouza/jamonapi#7]
Hello,

I would like to monitor the exceptions thrown in a Java application (e.g. in a package). The application uses Log4J for logging. Monitoring could be appended in the log (e.g., providing stats of the number of the exception thrown by each class or in the package, or splitting the stats by the specific exception)

According to the documentation of JAMon, it should be possible to add an ExceptionBufferListener to the JAMonListenerFactory. Anyway, I don't see any specific implementation for this listener.

Can you address me to the part that handles this feature?
R

**Comment by stevensouza** [comment]
Sounds interesting. 
-  Here is some info about monitors though it doesn't show how to create one.  http://jamonapi.sourceforge.net/jamonlisteners.html
-  Jamon listeners implement this interface.  https://github.com/stevensouza/jamonapi/blob/master/jamon/src/main/java/com/jamonapi/JAMonListener.java
-  To put your listener into jamon to be used by jamon you call the static method 'JAMonListenerFactory.put(JAMonListener)'.  This class is also how I put the default jamon listeners into the factory, so you can see examples here.: https://github.com/stevensouza/jamonapi/blob/master/jamon/src/main/java/com/jamonapi/JAMonListenerFactory.java#L84
- At this point your listener is available to the jamon.war gui or...
- You can add the listener programmatically similar to this: http://jamonapi.sourceforge.net/jamonlisteners.html#monkey
-  This test adds a composite listener and so should give you an idea how to add a listener.  The 'createListenerType' method creates a complex composite ListenerType, but this is basically how it would work for you to although you wouldn't need to create a CompositeListener.  https://github.com/stevensouza/jamonapi/blob/master/jamon/src/test/java/com/jamonapi/ListenerTypeTest.java
-  You would want to add a 'value' listener.

Actually, I should probably have a test for doing what you want to do, so I can create one for you when I have a little more time.  Let me know if that would help. Or you could create a test and put it in 'JAMonListenerFactoryTest' and I could merge it.

I would also like to point you to automon.org.  It is an open source project I created recently that uses AOP to monitor any method/class/package and it will also track exceptions.  It requires no coding changes and so should be easy to get working. Automon has poms for sample programs. Let me know if you have any questions.
-  www.automon.org
-  article is at: http://jaxenter.com/advanced-java-monitoring-with-automon-116079.html

Steve

**Comment by robertotru** [comment]
Hey, thanks a lot for the complete answer.
Now, I'm trying automon. Nice one. 
Anyway, I'll probably investigate JAMon in the next days. Even if some coding is required, I think that it could be more flexible for exception tracking. So, I'll watch this repository looking for any new update.

Best

**Comment by stevensouza** [comment]
Great. Also, before coding make sure you see what jamon already does.  For example each specific exception type is counted.  You could add jamon listeners that parse the stacktrace (not sure but probably available via mon.getMonKey().getDetails()) to get the package, class etc.  You could create monitors in the listener for the package and class (MonitorFactory.add(packageStr, "Exceptions", 1), or you could add the details to be able to view the full stack trace.  

If you need help let me know.

Steve

**Comment by stevensouza** [comment]
Also if you use Spring you can try the jamon/spring aop capability to monitor your spring beans and exceptions.  Automon is like this but more general and allows you to monitor any method on any class whether it is spring or not.

Steve

**Comment by stevensouza** [comment]
And also I would like to know how your project turns out.  Good luck!

**Comment by stevensouza** [comment]
How is this coming along? Do you need any help?

**Comment by robertotru** [comment]
Hi Steven,

Sorry for the late answer, I had 3 weeks vacation and I get back just
yesterday.

I didn't tried yet Jamon nor Automon. I did some preliminary tests with the
AspectJ module from Spring and I'm not so happy.  We have an application
that has dozens modules and for the complex ones it had a lot of autowiring
issues. I would like to test Jamon and Automon, but my boss is now focused
on two tools thay are pushed from the top, Hystrix and Takipi, that we
should use together.  This is not mandatory anyway, since we are moving
towards microservices.

I'll keep you posted.
Roberto
Il 06/Ago/2015 23:00, "Steve Souza" notifications@github.com ha scritto:
